# Homebrew Package Management
# ===========================
# All Homebrew taps, formulae, casks, and Mac App Store apps.
# Imported by flake.nix as a nix-darwin module.

{ pkgs, ... }:

{
  homebrew = {
    enable = true;
    onActivation.cleanup = "uninstall";

    taps = [
      "antoniorodr/memo"
      "charmbracelet/tap"
      "qrun-io/qctl"
      "steipete/tap"
    ];

    # masApps are intentionally commented out (mas CLI unreliable on recent macOS).
    # Uncomment individually after signing into the Mac App Store.
    masApps = {
      ## Xcode                         = 497799835;
      ## airmail-lightning-fast-email  = 918858936;
      ## blackmagic-disk-speed-test    = 425264550;
      ## ivory-for-mastodon-by-tapbots = 6444602274;
      ## keynote                       = 409183694;
      ## lanscan                       = 472226235;
      ## numbers                       = 409203825;
      ## pages                         = 409201541;
      ## pagesi                        = 409201541;
      ## parcel-delivery-tracking      = 639968404;
      ## whatsapp-messenger            = 310633997;
      ##wireguard                     = 1451685025;
    };

    brews = [
      "ack"
      "act"
      "age"
      "aerc"
      "aicommits"
      "ansible"
      "ansible-creator"
      "ansible-lint"
      "argocd"
      "arping"
      "asciiquarium"
      "ast-grep"
      "awscli"
      "bash"
      "bfg"
      "binwalk"
      "boxes"
      "btop"
      "calicoctl"
      "cargo-spellcheck"
      "charmbracelet/tap/gum"
      "circleci"
      "clang-format"
      "cloc"
      "cmake"
      "cmatrix"
      "colima"
      "cmctl"
      "commitizen"
      "commitlint"
      "composer"
      "cosign"
      "coreutils"
      "coturn"
      "cowsay"
      "curl"
      "dialog"
      "difftastic"
      "doggo"
      "duf"
      "dust"
      "eksctl"
      "fastfetch"
      "fd"
      "ffmpeg"
      "fish"
      "fzf"
      "gh"
      "git"
      "git-absorb"
      "git-crypt"
      "git-lfs"
      "gitea"
      "gitleaks"
      "glow"
      "gnu-sed"
      "gnupg"
      "steipete/tap/gogcli"
      "go"
      "go-task"
      "gradle"
      # "gping" -- conflicts with inetutils; run `brew link --overwrite gping` manually
      "helm"
      "helmfile"
      "himalaya"
      "htop"
      "hyperfine"
      "imagemagick"
      "steipete/tap/imsg"
      "inetutils"
      "iperf3"
      "jq"
      "julia"
      "k9s"
      "krew"
      "kubectx"
      "kubernetes-cli"
      "kubeseal"
      "kustomize"
      "lazydocker"
      "lazygit"
      "ldapvi"
      "liquibase"
      "llvm"
      "lua"
      "luarocks"
      "markdownlint-cli2"
      "mas"
      "maven"
      "antoniorodr/memo/memo"
      "mtr"
      "minio-mc"
      "mysql@8.4"
      "ncdu"
      "neovim"
      "ninja"
      "nmap"
      "node@22"
      "numpy"
      "openai-whisper"
      "openjdk@21"
      "opentofu"
      "pandoc"
      "steipete/tap/peekaboo"
      "pinentry-mac"
      "pipx"
      "platformio"
      "poppler"
      "postgresql@17"
      "procs"
      "pv"
      "pwgen"
      "python-packaging"
      "python@3.13"
      "pytorch"
      "qrun-io/qctl/qctl"
      "steipete/tap/remindctl"
      "ripgrep"
      "rust"
      "sd"
      "sdl2"
      "semgrep"
      "shellcheck"
      "sops"
      "sqlfluff"
      "sshpass"
      "stern"
      "stuntman"
      "steipete/tap/summarize"
      "talosctl"
      "terragrunt"
      "tokei"
      "tldr"
      "tmux"
      "tree"
      "tty-clock"
      "uv"
      "velero"
      "w3m"
      "watch"
      "weasyprint"
      "wget"
      "wimlib"
      "wireshark"
      "xh"
      "yamllint"
      "yq"
      "zlib"
    ];

    casks = [
      "1password"
      "1password-cli"
      "adobe-creative-cloud"
      "alfred"
      "alt-tab"
      "arc"
      "aws-vpn-client"
      "backblaze"
      "balenaetcher"
      "bettertouchtool"
      "claude-code"
      "cleanshot"
      "connectmenow"
      "dbeaver-community"
      "devonthink"
      "docker-desktop"
      "drawio"
      "ecamm-live"
      "elgato-camera-hub"
      "elgato-stream-deck"
      "fantastical"
      "github"
      "graalvm-jdk"
      "graalvm-jdk@21"
      "intellij-idea"
      "istat-menus"
      "jump-desktop"
      "karabiner-elements"
      "keyboard-maestro"
      "lens"
      "loopback"
      "mactex-no-gui"
      "obsidian"
      "omnifocus"
      "omnigraffle"
      "omniplan"
      "openwebstart"
      "rustdesk"
      "session-manager-plugin"
      "slack"
      "tailscale-app"
      "tunnelblick"
      "visual-studio-code"
      "warp"
      "wezterm"
      "wireshark-chmodbpf"
      "zoom"
    ];
  };
}
