# Homebrew Package Management
# ===========================
# All Homebrew taps, formulae, casks, and Mac App Store apps.
# Imported by flake.nix as a nix-darwin module.

{ pkgs, ... }:

{
  homebrew = {
    enable = true;
    onActivation.cleanup = "uninstall";
    # Auto-upgrade all brew formulae and casks on every `darwin-rebuild switch`.
    # Keeps AI tools (claude, codex, gemini-cli, aicommits, ollama-app, openai-whisper)
    # current; also upgrades all other brews as a side effect.
    onActivation.upgrade = true;
    # Refresh brew's package metadata before upgrading so we pull the latest versions.
    onActivation.autoUpdate = true;

    taps = [
      "antoniorodr/memo"
      "charmbracelet/tap"
      "qrun-io/qctl"
      "steipete/tap"
    ];

    # Mac App Store apps (managed via mas CLI 6.0+)
    masApps = {
      "1Password for Safari"         = 1569813296;
      "Airmail"                      = 918858936;
      "GarageBand"                   = 682658836;
      "iMovie"                       = 408981434;
      "Keynote"                      = 409183694;
      "Numbers"                      = 409203825;
      "Pages"                        = 409201541;
      "Parcel - Delivery Tracking"   = 375589283;
      "Xcode"                        = 497799835;
    };

    brews = [
      "ack"
      "act"
      "age"
      "aerc"
      "aicommits"
      "ansible"
      "ansible-creator"
      "ansible-lint"
      "argocd"
      "arping"
      "asciiquarium"
      "ast-grep"
      "awscli"
      "bash"
      "bfg"
      "binwalk"
      "boxes"
      "btop"
      "calicoctl"
      "cargo-spellcheck"
      "cbonsai"
      "charmbracelet/tap/gum"
      "circleci"
      "cloudflare-speed-cli"
      "clang-format"
      "cloc"
      "cmake"
      "cmatrix"
      "colima"
      "cmctl"
      "commitizen"
      "commitlint"
      "composer"
      "cosign"
      "coreutils"
      "coturn"
      "cowsay"
      "curl"
      "dialog"
      "difftastic"
      "dua-cli"
      "doggo"
      "duf"
      "dust"
      "eksctl"
      "fastfetch"
      "fd"
      "firebase-cli"
      "ffmpeg"
      "gemini-cli"
      "fish"
      "fzf"
      "gh"
      "git"
      "git-absorb"
      "git-crypt"
      "git-lfs"
      "gitea"
      "gitleaks"
      "gdu"
      "genact"
      "glow"
      "gnu-sed"
      "gnupg"
      "steipete/tap/gogcli"
      "go"
      "go-task"
      "gradle"
      "gping"
      "helm"
      "helmfile"
      "himalaya"
      "htop"
      "hyperfine"
      "imagemagick"
      "steipete/tap/imsg"
      { name = "inetutils"; link = false; }
      "iperf3"
      "jq"
      "julia"
      "k9s"
      "krew"
      "kubectx"
      "kubernetes-cli"
      "kubeseal"
      "kustomize"
      "lazydocker"
      "lavat"
      "lazygit"
      "ldapvi"
      "liquibase"
      "llvm"
      "lua"
      "luarocks"
      "markdownlint-cli2"
      "mas"
      "maven"
      "antoniorodr/memo/memo"
      "mtr"
      "minio-mc"
      "mysql@8.4"
      "ncdu"
      "neovim"
      "ninja"
      "no-more-secrets"
      "nmap"
      "node@20"
      "node@22"
      "numpy"
      "openai-whisper"
      "opencode"
      "openjdk@21"
      "opentofu"
      "pandoc"
      "steipete/tap/peekaboo"
      "pinentry-mac"
      "pipes-sh"
      "pipx"
      "platformio"
      "poppler"
      "prettyping"
      "postgresql@17"
      "procs"
      "pv"
      "pwgen"
      "python-packaging"
      "python@3.13"
      "pytorch"
      "qrun-io/qctl/qctl"
      "steipete/tap/remindctl"
      "ripgrep"
      "rust"
      "sd"
      "sdl2"
      "semgrep"
      "shellcheck"
      "sops"
      "sqlfluff"
      "sshpass"
      "stern"
      "stuntman"
      "talosctl"
      "terragrunt"
      "tokei"
      "tldr"
      "tmux"
      "tree"
      "tty-clock"
      "uv"
      "velero"
      "w3m"
      "watch"
      "weasyprint"
      "wget"
      "wimlib"
      "wireshark"
      "xcodegen"
      "xh"
      "yamllint"
      "yq"
      "zlib"
    ];

    casks = [
      "1password"
      "1password-cli"
      "adobe-creative-cloud"
      "alfred"
      "alt-tab"
      "arc"
      "aws-vpn-client"
      "backblaze"
      "balenaetcher"
      "bambu-studio"
      "bettertouchtool"
      "claude"
      # claude-code: installed via npm (-g @anthropic-ai/claude-code) instead of Homebrew
      # Reason: Homebrew cask lags Anthropic's release cadence. npm gives same-day releases.
      "cleanshot"
      "codex"
      "connectmenow"
      "dbeaver-community"
      "devonthink"
      "docker-desktop"
      "drawio"
      "ecamm-live"
      "elgato-camera-hub"
      "elgato-stream-deck"
      "fantastical"
      "github"
      "graalvm-jdk"
      "graalvm-jdk@21"
      "intellij-idea"
      "istat-menus"
      "jetbrains-toolbox"
      "jump-desktop"
      "karabiner-elements"
      "keyboard-maestro"
      "lens"
      "loopback"
      "mactex-no-gui"
      "notion-calendar"
      "notion-mail"
      "notion"
      "obsidian"
      "ollama-app"
      "omnifocus"
      "omnigraffle"
      "omniplan"
      "openwebstart"
      "rectangle"
      "rustdesk"
      "session-manager-plugin"
      "slack"
      "slack-cli"
      "tailscale-app"
      "viscosity"
      "typora"
      "visual-studio-code"
      "warp"
      "wezterm"
      "wireshark-chmodbpf"
      "zoom"
    ];
  };
}
