# Antigravity CLI Module
# ======================
# Installs Google's Antigravity CLI (`agy`) — the Go-based coding agent that
# replaces Gemini CLI as of Google I/O 2026 (Gemini CLI sunsets 2026-06-18).
#
# Files / paths involved:
#   - Binary: ~/.local/bin/agy            (installer drops it here, no sudo)
#   - Cache:  ~/.cache/antigravity/staging (transient; installer reaps on exit)
#   - Global config: ~/.gemini/antigravity-cli/  (shared dir with Gemini CLI;
#                                                  intentional, Antigravity reads
#                                                  here on first run)
#
# Why activation-based instead of a Nix derivation:
#   Antigravity is a fast-moving Google release, manifest-driven, with SHA512
#   verification baked into install.sh. Re-implementing the manifest fetch in
#   Nix would chase a moving target. Same tradeoff already accepted in
#   home/hermes/default.nix.
#
# Dependencies (declared elsewhere):
#   - curl (system / Homebrew)
#   - ~/.local/bin on PATH (home/default.nix sessionPath)
#
# Updating: the binary self-updates in the background during regular runs;
# `agy-update` forces a fresh re-install by removing the binary first.
# Activation only runs the installer when the binary is missing — re-running
# install.sh on every rebuild would hit the network unnecessarily.

{ config, pkgs, lib, ... }:

let
  homeDir = config.home.homeDirectory;
  brewBin = "/opt/homebrew/bin";
  agyBin = "${homeDir}/.local/bin/agy";
  installerUrl = "https://antigravity.google/cli/install.sh";

  # Declarative configuration for the Antigravity CLI
  antigravitySettings = {
    allowNonWorkspaceAccess = true;
    colorScheme = "colorblind-friendly dark";
    enableTelemetry = false;
    permissions = {
      allow = [
        "command(agy)"
        "command(cat)"
        "command(darwin-rebuild)"
        "command(env)"
        "command(git add)"
        "command(git commit)"
        "command(git diff)"
        "command(git status)"
        "command(head)"
        "command(id)"
        "command(jq)"
        "command(launchctl print)"
        "command(ls)"
        "command(mv)"
        "command(open)"
        "command(pwd)"
        "command(~/.local/bin/check-updates.sh)"
        "command(~/.local/bin/git-pane-info.sh)"
        "read_file(${homeDir}/.ai)"
        "read_file(${homeDir}/.gemini/GEMINI.md)"
      ];
    };
    trustedWorkspaces = [
      "${homeDir}/.config/nix"
    ];
  };

  antigravitySettingsJson = pkgs.writeText "antigravity-settings.json" (builtins.toJSON antigravitySettings);

  # Windows variant (LORE bridge): same policy, Windows paths. agy comes from
  # scoop (windows/scoop.json); config dir is %USERPROFILE%\.gemini\antigravity-cli.
  winAntigravitySettings = antigravitySettings // {
    permissions = {
      allow = [
        "command(agy)"
        "command(cat)"
        "command(env)"
        "command(git add)"
        "command(git commit)"
        "command(git diff)"
        "command(git status)"
        "command(head)"
        "command(jq)"
        "command(ls)"
        "command(mv)"
        "command(pwd)"
        "read_file(C:/Users/james/.ai)"
        "read_file(C:/Users/james/.gemini/GEMINI.md)"
      ];
    };
    trustedWorkspaces = [
      "R:/Git.Local/KofTwentyTwo/nix"
    ];
  };
  winAntigravitySettingsJson = pkgs.writeText "antigravity-settings-windows.json" (builtins.toJSON winAntigravitySettings);

  # MCP servers. Antigravity reads a SEPARATE global file (per its bundled
  # docs/mcp_servers.md): ~/.gemini/config/mcp_config.json with a `mcpServers`
  # map. Same shared set gemini uses (home/lib/mcp-servers.nix) — see that file
  # for the env-inheritance auth model (GITHUB_TOKEN/CIRCLECI_TOKEN/
  # FIRECRAWL_API_KEY must be in the launching environment).
  mcpConfigJson = pkgs.writeText "antigravity-mcp-config.json"
    (builtins.toJSON { mcpServers = import ../lib/mcp-servers.nix { }; });
in
{
  # Manual updater. Forces a clean reinstall of the latest published binary.
  home.file.".local/bin/agy-update" = {
    executable = true;
    text = ''
      #!/usr/bin/env bash
      # Auto-generated by home/antigravity/default.nix. Do not edit directly.
      set -euo pipefail
      # /usr/bin and /bin needed because install.sh calls curl, tar, shasum,
      # xattr -- all of which live in /usr/bin on macOS, not under brewBin.
      # Home Manager activation starts with a minimal nix-store-only PATH, so
      # without this the `command -v curl` check below fails silently.
      export PATH="${brewBin}:/usr/bin:/bin:$PATH"

      if [ -x "${agyBin}" ]; then
        echo "==> Removing existing ${agyBin}"
        rm -f "${agyBin}"
      fi

      echo "==> Fetching latest agy via ${installerUrl}"
      curl -fsSL "${installerUrl}" | bash

      if [ -x "${agyBin}" ]; then
        echo "Done. agy --version:"
        "${agyBin}" --version || true
      else
        echo "agy-update: install completed but ${agyBin} is missing" >&2
        exit 1
      fi
    '';
  };

  # First-time installer. Skipped if `agy` already exists (the upstream binary
  # self-updates in the background during normal runs — re-running install.sh
  # on every switch would re-hit the network unnecessarily).
  #
  # Subshell-scoped PATH: Home Manager concatenates every home.activation.*
  # block into one bash process, so an unscoped `export PATH=...` leaks into
  # every later activation. Run inside ( ... ) so the PATH change dies with
  # this activation.
  #
  # Never use bare `exit 0` to skip a step here — same hazard documented in
  # home/hermes/default.nix and home/claude/default.nix (kills downstream
  # activations).
  home.activation.installAntigravity = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    (
      # /usr/bin and /bin needed because install.sh calls curl, tar, shasum,
      # xattr -- all of which live in /usr/bin on macOS, not under brewBin.
      # Home Manager activation starts with a minimal nix-store-only PATH, so
      # without this the `command -v curl` check below fails silently.
      export PATH="${brewBin}:/usr/bin:/bin:$PATH"

      if [ -x "${agyBin}" ]; then
        : # already installed; agy self-updates in background
      elif ! command -v curl >/dev/null 2>&1; then
        echo "antigravity: curl not found on PATH; skipping install" >&2
      else
        echo "antigravity: installing to ${agyBin} via upstream install.sh"
        curl -fsSL "${installerUrl}" | bash \
          || echo "antigravity: WARN install failed (offline?); rerun darwin-rebuild switch when network is available" >&2
      fi
    )
  '';

  # ~/.gemini/antigravity-cli/settings.json - merge settings, preserve other allowed commands
  home.activation.syncAntigravitySettings = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    agy_json="${homeDir}/.gemini/antigravity-cli/settings.json"
    mkdir -p "${homeDir}/.gemini/antigravity-cli"

    if [ ! -f "$agy_json" ] || [ ! -s "$agy_json" ]; then
      ${pkgs.jq}/bin/jq -n --slurpfile settings "${antigravitySettingsJson}" '$settings[0]' > "$agy_json"
      chmod 600 "$agy_json"
    else
      if ${pkgs.jq}/bin/jq --slurpfile settings "${antigravitySettingsJson}" '
        .allowNonWorkspaceAccess = $settings[0].allowNonWorkspaceAccess
        | .colorScheme = $settings[0].colorScheme
        | .enableTelemetry = $settings[0].enableTelemetry
        | .permissions.allow = ((.permissions.allow // []) + $settings[0].permissions.allow | unique)
        | .trustedWorkspaces = ((.trustedWorkspaces // []) + $settings[0].trustedWorkspaces | unique)
      ' "$agy_json" > "$agy_json.tmp" \
        && [ -s "$agy_json.tmp" ]; then
        mv "$agy_json.tmp" "$agy_json"
        chmod 600 "$agy_json"
      else
        rm -f "$agy_json.tmp"
      fi
    fi
  '';

  # LORE bridge: same settings merge against the Windows profile copy.
  home.activation.syncWindowsAntigravity = lib.mkIf pkgs.stdenv.isLinux (lib.hm.dag.entryAfter [ "syncAntigravitySettings" ] ''
    win="/mnt/c/Users/james/.gemini/antigravity-cli"
    if [ -d "/mnt/c/Users/james" ]; then
      mkdir -p "$win"
      waj="$win/settings.json"
      if [ ! -f "$waj" ] || [ ! -s "$waj" ]; then
        ${pkgs.jq}/bin/jq -n --slurpfile settings "${winAntigravitySettingsJson}" '$settings[0]' > "$waj"
      else
        if ${pkgs.jq}/bin/jq --slurpfile settings "${winAntigravitySettingsJson}" '
          .allowNonWorkspaceAccess = $settings[0].allowNonWorkspaceAccess
          | .colorScheme = $settings[0].colorScheme
          | .enableTelemetry = $settings[0].enableTelemetry
          | .permissions.allow = ((.permissions.allow // []) + $settings[0].permissions.allow | unique)
          | .trustedWorkspaces = ((.trustedWorkspaces // []) + $settings[0].trustedWorkspaces | unique)
        ' "$waj" > "$waj.tmp" && [ -s "$waj.tmp" ]; then
          mv "$waj.tmp" "$waj"
        else
          rm -f "$waj.tmp"
        fi
      fi
      echo "[antigravity-win] settings mirrored"
    fi
  '');

  # ~/.gemini/config/mcp_config.json — antigravity's global MCP server config.
  # Fully declarative (no user-merge): we own this file. Written as a real file
  # (mode 600), not a symlink, so the Windows bridge can copy it.
  home.activation.syncAntigravityMcp = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    mkdir -p "${homeDir}/.gemini/config"
    cp -f "${mcpConfigJson}" "${homeDir}/.gemini/config/mcp_config.json"
    chmod 600 "${homeDir}/.gemini/config/mcp_config.json"
  '';

  # LORE bridge: same MCP config for Windows-native agy. --no-preserve strips
  # the store's read-only mode (drvfs would map 0444 to the Windows RO attr).
  home.activation.syncWindowsAntigravityMcp = lib.mkIf pkgs.stdenv.isLinux
    (lib.hm.dag.entryAfter [ "syncAntigravityMcp" ] ''
      win="/mnt/c/Users/james/.gemini/config"
      if [ -d "/mnt/c/Users/james" ]; then
        mkdir -p "$win"
        cp -f --no-preserve=mode,ownership "${mcpConfigJson}" "$win/mcp_config.json"
        echo "[antigravity-win] mcp_config.json mirrored"
      fi
    '');
}
