# Antigravity CLI Module
# ======================
# Installs Google's Antigravity CLI (`agy`) — the Go-based coding agent that
# replaces Gemini CLI as of Google I/O 2026 (Gemini CLI sunsets 2026-06-18).
#
# Files / paths involved:
#   - Binary: ~/.local/bin/agy            (installer drops it here, no sudo)
#   - Cache:  ~/.cache/antigravity/staging (transient; installer reaps on exit)
#   - Global config: ~/.gemini/antigravity-cli/  (shared dir with Gemini CLI;
#                                                  intentional, Antigravity reads
#                                                  here on first run)
#
# Why activation-based instead of a Nix derivation:
#   Antigravity is a fast-moving Google release, manifest-driven, with SHA512
#   verification baked into install.sh. Re-implementing the manifest fetch in
#   Nix would chase a moving target. Same tradeoff already accepted in
#   home/hermes/default.nix.
#
# Dependencies (declared elsewhere):
#   - curl (system / Homebrew)
#   - ~/.local/bin on PATH (home/default.nix sessionPath)
#
# Updating: the binary self-updates in the background during regular runs;
# `agy-update` forces a fresh re-install by removing the binary first.
# Activation only runs the installer when the binary is missing — re-running
# install.sh on every rebuild would hit the network unnecessarily.

{ config, pkgs, lib, ... }:

let
  homeDir = config.home.homeDirectory;
  brewBin = "/opt/homebrew/bin";
  agyBin = "${homeDir}/.local/bin/agy";
  installerUrl = "https://antigravity.google/cli/install.sh";
in
{
  # Manual updater. Forces a clean reinstall of the latest published binary.
  home.file.".local/bin/agy-update" = {
    executable = true;
    text = ''
      #!/usr/bin/env bash
      # Auto-generated by home/antigravity/default.nix. Do not edit directly.
      set -euo pipefail
      # /usr/bin and /bin needed because install.sh calls curl, tar, shasum,
      # xattr -- all of which live in /usr/bin on macOS, not under brewBin.
      # Home Manager activation starts with a minimal nix-store-only PATH, so
      # without this the `command -v curl` check below fails silently.
      export PATH="${brewBin}:/usr/bin:/bin:$PATH"

      if [ -x "${agyBin}" ]; then
        echo "==> Removing existing ${agyBin}"
        rm -f "${agyBin}"
      fi

      echo "==> Fetching latest agy via ${installerUrl}"
      curl -fsSL "${installerUrl}" | bash

      if [ -x "${agyBin}" ]; then
        echo "Done. agy --version:"
        "${agyBin}" --version || true
      else
        echo "agy-update: install completed but ${agyBin} is missing" >&2
        exit 1
      fi
    '';
  };

  # First-time installer. Skipped if `agy` already exists (the upstream binary
  # self-updates in the background during normal runs — re-running install.sh
  # on every switch would re-hit the network unnecessarily).
  #
  # Subshell-scoped PATH: Home Manager concatenates every home.activation.*
  # block into one bash process, so an unscoped `export PATH=...` leaks into
  # every later activation. Run inside ( ... ) so the PATH change dies with
  # this activation.
  #
  # Never use bare `exit 0` to skip a step here — same hazard documented in
  # home/hermes/default.nix and home/claude/default.nix (kills downstream
  # activations).
  home.activation.installAntigravity = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    (
      # /usr/bin and /bin needed because install.sh calls curl, tar, shasum,
      # xattr -- all of which live in /usr/bin on macOS, not under brewBin.
      # Home Manager activation starts with a minimal nix-store-only PATH, so
      # without this the `command -v curl` check below fails silently.
      export PATH="${brewBin}:/usr/bin:/bin:$PATH"

      if [ -x "${agyBin}" ]; then
        : # already installed; agy self-updates in background
      elif ! command -v curl >/dev/null 2>&1; then
        echo "antigravity: curl not found on PATH; skipping install" >&2
      else
        echo "antigravity: installing to ${agyBin} via upstream install.sh"
        curl -fsSL "${installerUrl}" | bash \
          || echo "antigravity: WARN install failed (offline?); rerun darwin-rebuild switch when network is available" >&2
      fi
    )
  '';
}
