# NPM Globals Module
# ==================
# Declaratively manage globally-installed npm packages in a user-owned prefix
# (~/.npm-global) so they don't conflict with Homebrew's node tree.
#
# Why npm instead of Homebrew for these packages:
#   Homebrew casks/formulae lag upstream release cadence (sometimes days).
#   npm pulls directly from the publisher's registry -> same-day releases.
#
# How it works:
#   - NPM_CONFIG_PREFIX=~/.npm-global puts all -g installs under the user dir
#   - ~/.npm-global/bin is prepended to PATH (wins over /opt/homebrew/bin)
#   - Activation script installs `pkg@latest` on every `darwin-rebuild switch`,
#     so declared AI CLIs stay fresh (same rationale as brew's
#     onActivation.upgrade). A `npm-globals-update` helper stays for manual runs.

{ config, pkgs, lib, ... }:

let
  homeDir = config.home.homeDirectory;

  # Declared global npm packages. Add entries here to have them installed
  # automatically on darwin-rebuild switch.
  packages = [
    "@anthropic-ai/claude-code"
  ];

  # Node.js bin dir from Homebrew (node@22 in modules/homebrew.nix).
  # We reference it directly so the activation script works even if PATH
  # isn't yet set up (activation runs before login shell init).
  nodeBin = "/opt/homebrew/opt/node@22/bin";

  packageList = lib.concatStringsSep " " packages;
in
{
  # User-owned npm prefix. Inherited by every shell so interactive
  # `npm install -g foo` also lands here, not in /opt/homebrew.
  home.sessionVariables = {
    NPM_CONFIG_PREFIX = "${homeDir}/.npm-global";
  };

  # Put ~/.npm-global/bin early on PATH. Home Manager prepends sessionPath
  # entries, so this wins over the Homebrew-managed bins listed in
  # home/default.nix.
  home.sessionPath = [
    "${homeDir}/.npm-global/bin"
  ];

  # Explicit updater script. Run `npm-globals-update` to pull @latest for
  # every declared package. Kept separate from activation so rebuilds
  # don't hit the network every time.
  home.file.".local/bin/npm-globals-update" = {
    executable = true;
    text = ''
      #!/usr/bin/env bash
      # Auto-generated by home/npm-globals/default.nix. Do not edit directly —
      # add packages to the `packages` list in that module instead.
      set -euo pipefail
      export NPM_CONFIG_PREFIX="${homeDir}/.npm-global"
      export PATH="${nodeBin}:$PATH"
      mkdir -p "$NPM_CONFIG_PREFIX"

      for pkg in ${packageList}; do
        echo "==> Updating $pkg to @latest"
        "${nodeBin}/npm" install -g "$pkg@latest"
      done
      echo "Done. Versions:"
      for pkg in ${packageList}; do
        # Strip scope for binary name guess; user can check specific bins themselves.
        "${nodeBin}/npm" ls -g --depth=0 "$pkg" 2>/dev/null || true
      done
    '';
  };

  # Install/upgrade declared packages on every rebuild. Always resolves to
  # @latest so AI CLIs stay current. npm's install is idempotent when the
  # package is already at the latest version, so this is cheap when nothing
  # changed. Non-fatal on network failures — logs a warning and continues.
  home.activation.installNpmGlobals = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    export NPM_CONFIG_PREFIX="${homeDir}/.npm-global"
    export PATH="${nodeBin}:$PATH"
    mkdir -p "$NPM_CONFIG_PREFIX"

    if [ ! -x "${nodeBin}/npm" ]; then
      echo "npm-globals: ${nodeBin}/npm not found; skipping (install node@22 via Homebrew first)" >&2
      exit 0
    fi

    for pkg in ${packageList}; do
      echo "npm-globals: installing/upgrading $pkg@latest"
      "${nodeBin}/npm" install -g "$pkg@latest" || \
        echo "npm-globals: WARN install of $pkg failed (offline?); continuing" >&2
    done
  '';
}
