#!/usr/bin/env bash
# git-help.sh - Show all custom git commands and aliases
set -uo pipefail

# Colors
BOLD='\033[1m'
CYAN='\033[0;36m'
GREEN='\033[0;32m'
MAGENTA='\033[0;35m'
DIM='\033[2m'
NC='\033[0m'

usage() {
    echo "Usage: $(basename "$0") [options]"
    echo ""
    echo "Options:"
    echo "  --mine    Show only custom commands"
    echo "  --omz     Show only oh-my-zsh aliases"
    echo "  -h        Show this help"
    exit 0
}

SHOW_MINE=true
SHOW_OMZ=true

while [[ $# -gt 0 ]]; do
    case "$1" in
        --mine) SHOW_OMZ=false; shift ;;
        --omz) SHOW_MINE=false; shift ;;
        -h|--help) usage ;;
        *) shift ;;
    esac
done

# Column widths
COL1=10   # alias
COL2=32   # command
COL3=50   # description

print_row() {
    local color="$1"
    local alias="$2"
    local cmd="$3"
    local desc="$4"
    printf "  ${color}%-${COL1}s${NC} ${DIM}%-${COL2}s${NC} %s\n" "$alias" "$cmd" "$desc"
}

if [[ "$SHOW_MINE" == true ]]; then
    echo -e "${BOLD}=== Custom Git Commands ===${NC}"
    echo ""
    print_row "$CYAN" "gsa"   "git-sync-all.sh"      "Morning sync: fetch, switch to latest branch, pull all repos"
    print_row "$CYAN" "gsall" "git-status-all.sh"    "Show status of all git repos in current directory"
    print_row "$CYAN" "gclo"  "git-clone-all.sh"     "Clone all repositories from a GitHub organization (uses SSH by default)"
    print_row "$CYAN" "gfa"   "git-fetch-all.sh"     "Fetch updates from remote for all repos in current directory"
    print_row "$CYAN" "gpa"   "git-pull-all.sh"      "Pull updates for all clean repos (skips repos with uncommitted changes)"
    print_row "$CYAN" "gba"   "git-branch-all.sh"    "Display current branch for all repos with summary count"
    print_row "$CYAN" "gcoa"  "git-checkout-all.sh"  "Checkout specified branch in all repos that have it"
    print_row "$CYAN" "gla"   "git-log-all.sh"       "Show recent commits for all repos (default: 3, use -n to change)"
    print_row "$CYAN" "gi"    "git-info.sh"          "Show comprehensive repo info: branch, remotes, status, and clickable links"
    print_row "$CYAN" "ghelp" "git-help.sh"          "Display this help with all git aliases and commands"
    print_row "$GREEN" "gc"   "git cz c"             "Create commit using commitizen interactive prompts"
    print_row "$GREEN" "gt"   "gitops-publish.sh"    "Publish feature branch tag for GitOps deployment pipeline"
    echo ""
fi

if [[ "$SHOW_OMZ" == true ]]; then
    echo -e "${BOLD}=== Oh-My-Zsh Git Aliases ===${NC}"
    echo ""
    print_row "$MAGENTA" "g"        "git"                              "Run git command"
    print_row "$MAGENTA" "ga"       "git add"                          "Stage files for commit"
    print_row "$MAGENTA" "gaa"      "git add --all"                    "Stage all changes including untracked files"
    print_row "$MAGENTA" "gam"      "git am"                           "Apply patches from mailbox format"
    print_row "$MAGENTA" "gama"     "git am --abort"                   "Abort current patch application and restore original branch"
    print_row "$MAGENTA" "gamc"     "git am --continue"                "Continue applying patches after resolving conflicts"
    print_row "$MAGENTA" "gams"     "git am --skip"                    "Skip current patch and continue with remaining patches"
    print_row "$MAGENTA" "gap"      "git apply"                        "Apply a patch to files without creating a commit"
    print_row "$MAGENTA" "gapa"     "git add --patch"                  "Interactively choose hunks to stage"
    print_row "$MAGENTA" "gapt"     "git apply --3way"                 "Apply patch using 3-way merge if it fails"
    print_row "$MAGENTA" "gau"      "git add --update"                 "Stage modifications to already-tracked files only"
    print_row "$MAGENTA" "gav"      "git add --verbose"                "Stage files with verbose output showing what was added"
    print_row "$MAGENTA" "gb"       "git branch"                       "List local branches"
    print_row "$MAGENTA" "gbD"      "git branch -D"                    "Force delete a branch even if not fully merged"
    print_row "$MAGENTA" "gbd"      "git branch -d"                    "Delete a branch (only if fully merged)"
    print_row "$MAGENTA" "gbg"      "git branch -vv | grep gone"       "Show local branches whose upstream is gone"
    print_row "$MAGENTA" "gbgD"     "git branch gone | xargs -D"       "Force delete all branches whose upstream is gone"
    print_row "$MAGENTA" "gbgd"     "git branch gone | xargs -d"       "Delete all branches whose upstream is gone (if merged)"
    print_row "$MAGENTA" "gbl"      "git blame -w"                     "Show file blame ignoring whitespace changes"
    print_row "$MAGENTA" "gbm"      "git branch --move"                "Rename a branch"
    print_row "$MAGENTA" "gbnm"     "git branch --no-merged"           "List branches not yet merged into current branch"
    print_row "$MAGENTA" "gbr"      "git branch --remote"              "List remote-tracking branches"
    print_row "$MAGENTA" "gbs"      "git bisect"                       "Use binary search to find commit that introduced a bug"
    print_row "$MAGENTA" "gbsb"     "git bisect bad"                   "Mark current commit as bad during bisect"
    print_row "$MAGENTA" "gbsg"     "git bisect good"                  "Mark current commit as good during bisect"
    print_row "$MAGENTA" "gbsn"     "git bisect new"                   "Mark current commit as new (alternative to bad)"
    print_row "$MAGENTA" "gbso"     "git bisect old"                   "Mark current commit as old (alternative to good)"
    print_row "$MAGENTA" "gbsr"     "git bisect reset"                 "End bisect session and return to original HEAD"
    print_row "$MAGENTA" "gbss"     "git bisect start"                 "Start a new bisect session"
    print_row "$MAGENTA" "gc!"      "git commit --amend"               "Amend the most recent commit (edit message and content)"
    print_row "$MAGENTA" "gcB"      "git checkout -B"                  "Create or reset a branch to specified start point"
    print_row "$MAGENTA" "gca"      "git commit -a"                    "Commit all tracked modified files"
    print_row "$MAGENTA" "gca!"     "git commit -a --amend"            "Amend last commit including all tracked changes"
    print_row "$MAGENTA" "gcam"     "git commit -am"                   "Commit all tracked files with inline message"
    print_row "$MAGENTA" "gcan!"    "git commit -a --amend --no-edit"  "Amend last commit with all changes, keep message"
    print_row "$MAGENTA" "gcas"     "git commit -a -s"                 "Commit all tracked files with sign-off"
    print_row "$MAGENTA" "gcasm"    "git commit -a -s -m"              "Commit all tracked files with sign-off and message"
    print_row "$MAGENTA" "gcb"      "git checkout -b"                  "Create new branch and switch to it"
    print_row "$MAGENTA" "gcd"      "git checkout develop"             "Switch to develop branch"
    print_row "$MAGENTA" "gcf"      "git config --list"                "List all git configuration settings"
    print_row "$MAGENTA" "gcfu"     "git commit --fixup"               "Create fixup commit for use with rebase --autosquash"
    print_row "$MAGENTA" "gcl"      "git clone --recurse-submodules"   "Clone repository including all submodules"
    print_row "$MAGENTA" "gclean"   "git clean -id"                    "Interactively remove untracked files from working tree"
    print_row "$MAGENTA" "gcm"      "git checkout \$(main)"            "Switch to main branch (auto-detects main vs master)"
    print_row "$MAGENTA" "gcmsg"    "git commit -m"                    "Create commit with inline message"
    print_row "$MAGENTA" "gcn"      "git commit --no-edit"             "Commit without opening editor (use existing message)"
    print_row "$MAGENTA" "gcn!"     "git commit --amend --no-edit"     "Amend last commit without changing commit message"
    print_row "$MAGENTA" "gco"      "git checkout"                     "Switch branches or restore working tree files"
    print_row "$MAGENTA" "gcor"     "git checkout --recurse-submodules" "Checkout branch and update submodules"
    print_row "$MAGENTA" "gcount"   "git shortlog -sn"                 "Count commits per author in shortlog format"
    print_row "$MAGENTA" "gcp"      "git cherry-pick"                  "Apply changes from specific commits to current branch"
    print_row "$MAGENTA" "gcpa"     "git cherry-pick --abort"          "Abort cherry-pick and restore original branch state"
    print_row "$MAGENTA" "gcpc"     "git cherry-pick --continue"       "Continue cherry-pick after resolving conflicts"
    print_row "$MAGENTA" "gcs"      "git commit -S"                    "Create GPG-signed commit"
    print_row "$MAGENTA" "gcsm"     "git commit -s -m"                 "Create commit with sign-off and inline message"
    print_row "$MAGENTA" "gd"       "git diff"                         "Show changes between commits, working tree, etc."
    print_row "$MAGENTA" "gdca"     "git diff --cached"                "Show staged changes (same as --staged)"
    print_row "$MAGENTA" "gds"      "git diff --staged"                "Show changes staged for next commit"
    print_row "$MAGENTA" "gdt"      "git diff-tree --no-commit-id"     "Show changed files in a commit"
    print_row "$MAGENTA" "gdw"      "git diff --word-diff"             "Show diff with word-level granularity"
    print_row "$MAGENTA" "gf"       "git fetch"                        "Download objects and refs from remote repository"
    print_row "$MAGENTA" "gfo"      "git fetch origin"                 "Fetch from origin remote"
    print_row "$MAGENTA" "gfg"      "git ls-files | grep"              "Search for files tracked by git matching pattern"
    print_row "$MAGENTA" "gg"       "git gui citool"                   "Open git GUI for creating commits"
    print_row "$MAGENTA" "gga"      "git gui citool --amend"           "Open git GUI to amend last commit"
    print_row "$MAGENTA" "ghh"      "git help"                         "Display help information about git commands"
    print_row "$MAGENTA" "gl"       "git pull"                         "Fetch from remote and integrate with local branch"
    print_row "$MAGENTA" "glg"      "git log --stat"                   "Show commit logs with diffstat"
    print_row "$MAGENTA" "glgg"     "git log --graph"                  "Show commit logs with ASCII graph"
    print_row "$MAGENTA" "glgga"    "git log --graph --all"            "Show commit graph for all branches"
    print_row "$MAGENTA" "glgm"     "git log --graph --max-count=10"   "Show last 10 commits with graph"
    print_row "$MAGENTA" "glgp"     "git log --stat -p"                "Show commit logs with stats and patches"
    print_row "$MAGENTA" "glo"      "git log --oneline"                "Show commit logs with one line per commit"
    print_row "$MAGENTA" "glod"     "git log --oneline --decorate"     "Show oneline log with branch/tag decorations"
    print_row "$MAGENTA" "glog"     "git log --oneline --graph"        "Show oneline commit graph"
    print_row "$MAGENTA" "gloga"    "git log --oneline --graph --all"  "Show oneline commit graph for all branches"
    print_row "$MAGENTA" "glol"     "git log --graph --pretty"         "Show pretty-formatted commit graph"
    print_row "$MAGENTA" "glola"    "git log --graph --pretty --all"   "Show pretty commit graph for all branches"
    print_row "$MAGENTA" "glols"    "git log --graph --pretty --stat"  "Show pretty commit graph with stats"
    print_row "$MAGENTA" "glp"      "git log -p"                       "Show commit logs with full patches"
    print_row "$MAGENTA" "gm"       "git merge"                        "Join two or more development histories together"
    print_row "$MAGENTA" "gma"      "git merge --abort"                "Abort current merge and restore pre-merge state"
    print_row "$MAGENTA" "gmom"     "git merge origin/\$(main)"        "Merge origin's main branch into current branch"
    print_row "$MAGENTA" "gms"      "git merge --squash"               "Squash commits from branch into single commit"
    print_row "$MAGENTA" "gmtl"     "git mergetool --no-prompt"        "Run merge conflict resolution tool"
    print_row "$MAGENTA" "gmum"     "git merge upstream/\$(main)"      "Merge upstream's main branch into current branch"
    print_row "$MAGENTA" "gp"       "git push"                         "Update remote refs along with associated objects"
    print_row "$MAGENTA" "gpd"      "git push --delete"                "Delete a remote branch"
    print_row "$MAGENTA" "gpf"      "git push --force-with-lease"      "Force push safely (fails if remote has new commits)"
    print_row "$MAGENTA" "gpf!"     "git push --force"                 "Force push (overwrites remote - use with caution!)"
    print_row "$MAGENTA" "gpoat"    "git push origin --all --tags"     "Push all branches and tags to origin"
    print_row "$MAGENTA" "gpr"      "git pull --rebase"                "Pull and rebase local commits on top of upstream"
    print_row "$MAGENTA" "gpra"     "git pull --rebase --autostash"    "Pull with rebase, auto-stashing local changes"
    print_row "$MAGENTA" "gprom"    "git pull --rebase origin/\$(main)" "Rebase current branch onto origin's main"
    print_row "$MAGENTA" "gpsup"    "git push --set-upstream origin"   "Push branch and set up tracking for origin"
    print_row "$MAGENTA" "gpu"      "git push upstream"                "Push to upstream remote"
    print_row "$MAGENTA" "gpv"      "git push --verbose"               "Push with verbose output"
    print_row "$MAGENTA" "gr"       "git remote"                       "Manage set of tracked repositories"
    print_row "$MAGENTA" "gra"      "git remote add"                   "Add a new remote repository"
    print_row "$MAGENTA" "grb"      "git rebase"                       "Reapply commits on top of another base tip"
    print_row "$MAGENTA" "grba"     "git rebase --abort"               "Abort rebase and restore original branch"
    print_row "$MAGENTA" "grbc"     "git rebase --continue"            "Continue rebase after resolving conflicts"
    print_row "$MAGENTA" "grbi"     "git rebase -i"                    "Interactive rebase - edit, squash, reorder commits"
    print_row "$MAGENTA" "grbm"     "git rebase \$(main)"              "Rebase current branch onto main"
    print_row "$MAGENTA" "grbo"     "git rebase --onto"                "Rebase commits onto a different base"
    print_row "$MAGENTA" "grbom"    "git rebase origin/\$(main)"       "Rebase current branch onto origin's main"
    print_row "$MAGENTA" "grbs"     "git rebase --skip"                "Skip current commit and continue rebase"
    print_row "$MAGENTA" "grev"     "git revert"                       "Create new commit that undoes changes from a commit"
    print_row "$MAGENTA" "grh"      "git reset"                        "Reset current HEAD to specified state"
    print_row "$MAGENTA" "grhh"     "git reset --hard"                 "Reset HEAD, index, and working tree (destructive!)"
    print_row "$MAGENTA" "grhk"     "git reset --keep"                 "Reset HEAD but keep local changes if possible"
    print_row "$MAGENTA" "grhs"     "git reset --soft"                 "Reset HEAD only, keep index and working tree"
    print_row "$MAGENTA" "grm"      "git rm"                           "Remove files from working tree and index"
    print_row "$MAGENTA" "grmc"     "git rm --cached"                  "Remove files from index only, keep in working tree"
    print_row "$MAGENTA" "grmv"     "git remote rename"                "Rename a remote"
    print_row "$MAGENTA" "groh"     "git reset origin/HEAD"            "Reset branch to match origin's HEAD"
    print_row "$MAGENTA" "grrm"     "git remote remove"                "Remove a remote and its tracking branches"
    print_row "$MAGENTA" "grs"      "git restore"                      "Restore working tree files from index or commit"
    print_row "$MAGENTA" "grset"    "git remote set-url"               "Change URL for an existing remote"
    print_row "$MAGENTA" "grss"     "git restore --source"             "Restore file from specific commit or branch"
    print_row "$MAGENTA" "grst"     "git restore --staged"             "Unstage files (remove from index, keep changes)"
    print_row "$MAGENTA" "gru"      "git reset --"                     "Unstage specific file"
    print_row "$MAGENTA" "grup"     "git remote update"                "Fetch updates from all remotes"
    print_row "$MAGENTA" "grv"      "git remote -v"                    "List remotes with their URLs"
    print_row "$MAGENTA" "gsb"      "git status -sb"                   "Short status with branch and tracking info"
    print_row "$MAGENTA" "gsd"      "git svn dcommit"                  "Commit to SVN repository from git"
    print_row "$MAGENTA" "gsh"      "git show"                         "Show various types of objects (commits, tags, etc.)"
    print_row "$MAGENTA" "gsi"      "git submodule init"               "Initialize submodules in the repository"
    print_row "$MAGENTA" "gsps"     "git show --pretty=short"          "Show commit with abbreviated information"
    print_row "$MAGENTA" "gsr"      "git svn rebase"                   "Rebase git commits onto SVN"
    print_row "$MAGENTA" "gss"      "git status -s"                    "Short-format status output"
    print_row "$MAGENTA" "gst"      "git status"                       "Show working tree status"
    print_row "$MAGENTA" "gsta"     "git stash push"                   "Stash changes in working directory"
    print_row "$MAGENTA" "gstaa"    "git stash apply"                  "Apply stashed changes without removing from stash"
    print_row "$MAGENTA" "gstall"   "git stash --all"                  "Stash all files including untracked and ignored"
    print_row "$MAGENTA" "gstc"     "git stash clear"                  "Remove all stash entries"
    print_row "$MAGENTA" "gstd"     "git stash drop"                   "Remove single stash entry"
    print_row "$MAGENTA" "gstl"     "git stash list"                   "List all stash entries"
    print_row "$MAGENTA" "gstp"     "git stash pop"                    "Apply stashed changes and remove from stash"
    print_row "$MAGENTA" "gsts"     "git stash show -p"                "Show stash contents as a patch"
    print_row "$MAGENTA" "gstu"     "git stash -u"                     "Stash including untracked files"
    print_row "$MAGENTA" "gsu"      "git submodule update"             "Update submodules to recorded commits"
    print_row "$MAGENTA" "gsw"      "git switch"                       "Switch to a branch"
    print_row "$MAGENTA" "gswc"     "git switch -c"                    "Create and switch to a new branch"
    print_row "$MAGENTA" "gswm"     "git switch \$(main)"              "Switch to main branch"
    print_row "$MAGENTA" "gta"      "git tag -a"                       "Create annotated tag with message"
    print_row "$MAGENTA" "gts"      "git tag -s"                       "Create GPG-signed tag"
    print_row "$MAGENTA" "gtv"      "git tag | sort -V"                "List tags sorted by version number"
    print_row "$MAGENTA" "gunignore" "git update-index --no-assume"    "Stop ignoring changes to tracked file"
    print_row "$MAGENTA" "gunwip"   "git reset HEAD~1"                 "Undo last WIP commit, keep changes staged"
    print_row "$MAGENTA" "gup"      "git pull --rebase"                "Pull with rebase instead of merge"
    print_row "$MAGENTA" "gupa"     "git pull --rebase --autostash"    "Pull with rebase, auto-stash local changes"
    print_row "$MAGENTA" "gupav"    "git pull --rebase --autostash -v" "Pull with rebase and autostash, verbose"
    print_row "$MAGENTA" "gupom"    "git pull --rebase origin \$(main)" "Pull and rebase onto origin's main branch"
    print_row "$MAGENTA" "gupv"     "git pull --rebase -v"             "Pull with rebase, verbose output"
    print_row "$MAGENTA" "gwch"     "git whatchanged -p"               "Show what changed in each commit with patches"
    print_row "$MAGENTA" "gwip"     "git add -A && commit WIP"         "Stage all and create Work In Progress commit"
    print_row "$MAGENTA" "gwt"      "git worktree"                     "Manage multiple working trees"
    print_row "$MAGENTA" "gwta"     "git worktree add"                 "Create new working tree at specified path"
    print_row "$MAGENTA" "gwtls"    "git worktree list"                "List all working trees"
    print_row "$MAGENTA" "gwtmv"    "git worktree move"                "Move working tree to new location"
    print_row "$MAGENTA" "gwtrm"    "git worktree remove"              "Remove a working tree"
    echo ""
fi

if [[ "$SHOW_MINE" == true ]] && [[ "$SHOW_OMZ" == true ]]; then
    echo -e "${DIM}Filter: ghelp --mine | ghelp --omz | ghelp | grep <pattern>${NC}"
fi
