# Hermes Agent Module
# ===================
# Installs Nous Research's Hermes Agent — a Python-based single-agent runtime —
# on first activation. Code goes to ~/.hermes/hermes-agent; the upstream
# installer drops a `hermes` command in ~/.local/bin (already on PATH via
# sessionPath in home/default.nix).
#
# Why activation-based instead of a Nix derivation:
#   Hermes is a fast-moving Python project not packaged in nixpkgs/Homebrew.
#   Upstream's install.sh handles git clone + uv venv + dep sync — re-implementing
#   that in Nix would chase a moving target. Same tradeoff already accepted for
#   npm-managed AI CLIs in home/npm-globals/default.nix.
#
# Dependencies (declared elsewhere):
#   - uv (modules/homebrew.nix) — Python package manager used by Hermes
#   - git (Homebrew)
#   - ~/.local/bin on PATH (home/default.nix sessionPath)
#
# Updating: run `hermes-update` (git pull --ff-only + uv sync). Activation only
# runs the installer on first setup — re-running it on every rebuild would
# re-hit the network unnecessarily and risk surprising the user.

{ config, pkgs, lib, ... }:

let
  homeDir = config.home.homeDirectory;
  hermesHome = "${homeDir}/.hermes";
  installDir = "${hermesHome}/hermes-agent";
  hermesBin = "${homeDir}/.local/bin/hermes";

  # Homebrew prefix on Apple Silicon — used to locate uv/git/curl during
  # activation, which runs before login shell init populates PATH.
  brewBin = "/opt/homebrew/bin";
in
{
  # Manual updater. Pulls latest main and re-syncs the venv.
  home.file.".local/bin/hermes-update" = {
    executable = true;
    text = ''
      #!/usr/bin/env bash
      # Auto-generated by home/hermes/default.nix. Do not edit directly.
      set -euo pipefail
      export PATH="${brewBin}:$PATH"

      if [ ! -d "${installDir}/.git" ]; then
        echo "hermes-update: ${installDir} not found; run darwin-rebuild switch to install" >&2
        exit 1
      fi

      echo "==> Pulling latest in ${installDir}"
      git -C "${installDir}" pull --ff-only

      echo "==> Syncing venv"
      ( cd "${installDir}" && uv sync )

      if [ -x "${hermesBin}" ]; then
        echo "Done. hermes --version:"
        "${hermesBin}" --version || true
      fi
    '';
  };

  # First-time installer. Runs upstream install.sh with --skip-setup so the
  # interactive wizard doesn't block activation. Idempotent: skipped if
  # hermes-agent/.git already exists. Non-fatal on network failures so an
  # offline rebuild doesn't break.
  #
  # IMPORTANT: never use bare `exit 0` to skip a step here. Home-manager
  # concatenates every `home.activation.*` block into a single bash process,
  # so `exit 0` aborts the entire activation run — every activation that comes
  # alphabetically after `installHermesAgent` (notably syncClaudeJson, which
  # writes ~/.claude.json) silently never executes. Use if/elif/else with a
  # no-op (`:`) branch for the skip cases instead.
  home.activation.installHermesAgent = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    export PATH="${brewBin}:$PATH"

    if [ -d "${installDir}/.git" ]; then
      : # already installed; nothing to do
    elif ! command -v uv >/dev/null 2>&1; then
      echo "hermes: uv not found on PATH; install uv via Homebrew first (declared in modules/homebrew.nix)" >&2
    elif ! command -v git >/dev/null 2>&1; then
      echo "hermes: git not found on PATH; skipping install" >&2
    else
      echo "hermes: installing to ${installDir} via upstream install.sh (--skip-setup)"
      curl -fsSL https://raw.githubusercontent.com/NousResearch/hermes-agent/main/scripts/install.sh \
        | bash -s -- --skip-setup \
        || echo "hermes: WARN install failed (offline?); rerun darwin-rebuild switch when network is available" >&2
    fi
  '';
}
